# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: db-retriever-service
spec:
  selector:
    app: my-app2
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
